language: c
os:
    - linux
compiler:
    - clang
    - gcc
arch:
    - amd64
    - arm64
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install e2fsprogs; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y e2fslibs-dev uuid-dev ss-dev; fi
before_script:
    - autoreconf -vis
script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PKG_CONFIG_PATH="/usr/local/opt/e2fsprogs/lib/pkgconfig"; export PATH="/usr/local/opt/e2fsprogs/bin:$PATH"; fi
    - mkdir _b && cd _b
    - ../configure --prefix=$PWD/../_i
    - true cat config.h
    - make all check install installcheck
    - ls -lR
    - cd ..
    - ls -lR _i
    - (cd _b && make distcheck)
matrix:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty
